# compose yml for development env with hot reload

version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/hawiyat:/etc/hawiyat # binding host machine hawiyat configs
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
      - ./test-files:/app/test-files
      - /var/run/docker.sock:/var/run/docker.sock # binding the host machine docker socket to our container
    ports:
      - "8000:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1