# compose yml for development env with hot reload

version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # for dev hot reloading
      - ./src:/app/src 
      - ./scans:/app/scans 
      - ./test-files:/app/test-files
      - ./requirements.txt:/app/requirements.txt
      - ./tests:/app/tests

      - /etc/hawiyat:/etc/hawiyat # binding host machine hawiyat configs
      - /var/run/docker.sock:/var/run/docker.sock # binding the host machine docker socket to our container
    ports:
      - "8800:8800"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8800 --reload
    environment:
      - PYTHONUNBUFFERED=1