## my first docker compose file writtn by hand 
## docker stack doesn't build iamges so build them first and publish them or build locally 


#TO DO:
# use secrtets and healthchecks 
services:
  db:
    image: postgres:15-alpine  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
        - main-network

  redis:
    image: redis:alpine
    networks:
        - main-network

  vote:
    image: 0xkatana/vote:latest
    
    ports:
      - "8080:80"  
    depends_on:
      - redis
    networks:
      - main-network
    deploy:
      replicas: 2

  result:
    image : 0xkatana/result:latest
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - main-network

  worker:  
    image: 0xkatana/worker:latest
    depends_on:
      - db
      - redis
    networks:
      - main-network

networks:
  main-network:

volumes:
  postgres-data:
