name: Build, Scan, Push Docker Image ,

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    #if: contains(github.event.head_commit.message, 'build')
    runs-on: ubuntu-latest
    steps:
      # clone the code into the machine 
      - name: Checkout repository
        uses: actions/checkout@v3

      # set up docker on the machine 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # build the base (unoptimized) image
      - name: Build Docker image
        run: docker build -t security-core:${{ github.sha }} .

      # slim down the image
      - name: Optimize Docker image with SlimToolkit
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false   # disable probing if your app isn't web-based
        with:
          target: security-core:${{ github.sha }}
          tag: slim-${{ github.sha }}
          
      # log in to docker hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # push optimized image
      - name: Push Slimmed Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            0xkatana/security-core:latest
            0xkatana/security-core:${{ github.sha }}
            0xkatana/security-core:slim-${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=min
