name: Build, Scan,Push Docker Image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    if: contains(github.event.head_commit.message, 'build')
    runs-on: ubuntu-latest
    steps:
        # clone the code into the machine 
      - name: Checkout repository
        uses: actions/checkout@v3

        # set up docker on the machine 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

        # build the image localy 
      - name: Build Docker image
        run: docker build -t security-core:${{ github.sha }} .

        # image scaning for vulns
      - name: Scan Docker image for vulnerabilities (Trivy)
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: image
          image-ref: security-core:${{ github.sha }}
          format: sarif
          exit-code: 0
          severity: CRITICAL
          ignore-unfixed: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            0xkatana/security-core:latest
            0xkatana/security-core:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
